### PR TITLE
Add wifi modules and add code in main to turn on wifi hotspot

### PR DESCRIPTION
**Pull request by sofa13**

### CODE REVIEW

**Comment by SeanLF** [comment]
- Why is [driver.c](https://github.com/NsTremblay/real-time2016/blob/wifiModules2/driver.c) completely commented out?
- Do we need to add the USART [header](https://github.com/NsTremblay/real-time2016/blob/wifiModules2/include/usart_serial.h) and [.c](https://github.com/NsTremblay/real-time2016/blob/wifiModules2/usart_serial.c) files?

**Comment by sofa13** [comment]
driver.c is completely commented out for now because it's not being used and has a "main", which conflicts with our existing main.
usart header and .c file is necessary for the gain module and webserver modules, its slightly different from our existing usart module, and would be a pain to refractor to use just one usart module (I tried quickly, and saw it was a lot more work than just changing a couple lines)

**Comment by SeanLF** [comment]
- Then shouldn't we remove `driver.c` from the pull request if we aren't using it?
- :+1: re. the usart module.

**Comment by sofa13** [comment]
well we might use it later, I'm still not entirely sure what we need it for just yet.
nooo, i'm pretty sure we need both usart modules.

**Comment by morinted** [comment]
Yeah, the driver is just an empty template that you don't need. The teacher
told us as much in the emails he sent out.

**Comment by sofa13** [comment]
Merge pull request :D ?

**Pull request merged**
